"""BSNexus Pydantic schemas — re-exports everything for backward compatibility."""

from backend.src.schemas._legacy import (
    AddTaskRequest,
    AddTaskResponse,
    AuditLogListResponse,
    AuditLogResponse,
    BatchDeleteRequest,
    BatchDeleteResponse,
    BoardColumn,
    BoardResponse,
    BriefingResponse,
    ComplianceReportResponse,
    CreateSessionRequest,
    DashboardStatsResponse,
    DeleteResponse,
    DepsHealthResponse,
    DesignMessageResponse,
    DesignSessionResponse,
    DesignSessionStatus,
    FinalizeRequest,
    GlobalSettingsResponse,
    GlobalSettingsUpdate,
    HealthResponse,
    LLMConfigInput,
    MessageRequest,
    MessageRole,
    MigrateRequest,
    PhaseCreate,
    PhaseInfoResponse,
    PhaseRedesignRequest,
    PhaseRedesignResponse,
    PhaseResponse,
    PhaseStatus,
    PlanGenerateRequest,
    ProjectCreate,
    ProjectDashboardSummary,
    ProjectResponse,
    ProjectStatus,
    ProjectUpdate,
    SecurityFindingResponse,
    SecurityReportResponse,
    SignedPrompt,
    SuggestionApproveRequest,
    SuggestionModifyRequest,
    SuggestionRejectRequest,
    SuggestionStatus,
    TaskCreate,
    TaskPriority,
    TaskResponse,
    TaskSource,
    TaskStatus,
    TaskSuggestionCreate,
    TaskSuggestionResponse,
    TaskSuggestionUpdate,
    TaskTransition,
    TaskType,
    TaskUpdate,
    TransitionResponse,
)

# New schemas
from backend.src.schemas.agent import AgentCreate, AgentOrgChartResponse, AgentResponse, AgentUpdate
from backend.src.schemas.budget import AgentBudgetSummary, CostRecordCreate, CostRecordResponse
from backend.src.schemas.goal import GoalAncestryResponse, GoalCreate, GoalResponse, GoalUpdate
