"""add unique constraint on workers tenant_id + name for active

Revision ID: 0fbf942ea6c5
Revises: b06d1f663d08
Create Date: 2026-04-07 15:13:58.101608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fbf942ea6c5'
down_revision: Union[str, Sequence[str], None] = 'b06d1f663d08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_workers_tenant_name_active', 'workers', ['tenant_id', 'name'], unique=True, postgresql_where=sa.text('is_active = true'), sqlite_where=sa.text('is_active = 1'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_workers_tenant_name_active', table_name='workers', postgresql_where=sa.text('is_active = true'), sqlite_where=sa.text('is_active = 1'))
    # ### end Alembic commands ###
