"""add executor_config_id FK to agents

Revision ID: 344a8f79fb95
Revises: 98d193d23a51
Create Date: 2026-04-06 14:26:11.365713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '344a8f79fb95'
down_revision: Union[str, Sequence[str], None] = '98d193d23a51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('executor_config_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'agents', 'executor_configs', ['executor_config_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'agents', type_='foreignkey')
    op.drop_column('agents', 'executor_config_id')
    # ### end Alembic commands ###
