"""add company-os models: agents, tenants, goals, cost_records, workers and extend task/project/design_session

Revision ID: 7458151449d1
Revises: m5h6i7j8k9l0
Create Date: 2026-04-05 11:28:11.851213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7458151449d1'
down_revision: Union[str, Sequence[str], None] = 'm5h6i7j8k9l0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('mission', sa.Text(), nullable=True),
    sa.Column('owner_user_id', sa.String(length=255), nullable=False),
    sa.Column('plan', sa.String(length=50), server_default='free', nullable=False),
    sa.Column('settings', postgresql.JSON(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('api_key_hash', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('agents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('job_description', sa.Text(), nullable=True),
    sa.Column('executor_type', sa.String(length=50), server_default='claude_api', nullable=False),
    sa.Column('executor_config', postgresql.JSON(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('skills', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('capabilities', postgresql.JSON(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('parent_agent_id', sa.Uuid(), nullable=True),
    sa.Column('heartbeat_interval_seconds', sa.Integer(), nullable=True),
    sa.Column('heartbeat_enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('monthly_budget_cents', sa.Integer(), nullable=True),
    sa.Column('current_month_spent_cents', sa.Integer(), server_default='0', nullable=False),
    sa.Column('status', sa.String(length=50), server_default='offline', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agents_parent', 'agents', ['parent_agent_id'], unique=False)
    op.create_index('ix_agents_tenant', 'agents', ['tenant_id'], unique=False)
    op.create_index('ix_agents_tenant_role', 'agents', ['tenant_id', 'role'], unique=False)
    op.create_table('tenant_members',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), server_default='member', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tenant_members_tenant_user', 'tenant_members', ['tenant_id', 'user_id'], unique=True)
    op.create_index('ix_tenant_members_user', 'tenant_members', ['user_id'], unique=False)
    op.create_table('workers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('labels', postgresql.JSON(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('status', sa.String(length=50), server_default='offline', nullable=False),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=True),
    sa.Column('capabilities', postgresql.JSON(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_workers_status', 'workers', ['status'], unique=False)
    op.create_index('ix_workers_tenant', 'workers', ['tenant_id'], unique=False)
    op.create_table('goals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('parent_goal_id', sa.Uuid(), nullable=True),
    sa.Column('level', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('agent_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_goal_id'], ['goals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_goals_parent', 'goals', ['parent_goal_id'], unique=False)
    op.create_index('ix_goals_project', 'goals', ['project_id'], unique=False)
    op.create_index('ix_goals_tenant', 'goals', ['tenant_id'], unique=False)
    op.create_table('cost_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=True),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cost_records_agent', 'cost_records', ['agent_id'], unique=False)
    op.create_index('ix_cost_records_agent_month', 'cost_records', ['agent_id', 'recorded_at'], unique=False)
    op.create_index('ix_cost_records_tenant', 'cost_records', ['tenant_id'], unique=False)
    op.add_column('design_sessions', sa.Column('agent_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'design_sessions', 'agents', ['agent_id'], ['id'], ondelete='SET NULL')
    op.add_column('projects', sa.Column('max_concurrent_tasks', sa.Integer(), server_default='1', nullable=False))
    op.alter_column('task_history', 'from_status',
               existing_type=postgresql.ENUM('waiting', 'ready', 'queued', 'in_progress', 'review', 'done', 'redesign', name='taskstatus'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('task_history', 'to_status',
               existing_type=postgresql.ENUM('waiting', 'ready', 'queued', 'in_progress', 'review', 'done', 'redesign', name='taskstatus'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('task_suggestions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('task_suggestions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('tasks', sa.Column('agent_id', sa.Uuid(), nullable=True))
    op.add_column('tasks', sa.Column('goal_id', sa.Uuid(), nullable=True))
    op.add_column('tasks', sa.Column('output_type', sa.String(length=50), nullable=True))
    op.add_column('tasks', sa.Column('output_data', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.drop_index(op.f('ix_tasks_parent_task_id'), table_name='tasks')
    op.create_foreign_key(None, 'tasks', 'agents', ['agent_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'tasks', 'goals', ['goal_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_index(op.f('ix_tasks_parent_task_id'), 'tasks', ['parent_task_id'], unique=False)
    op.drop_column('tasks', 'output_data')
    op.drop_column('tasks', 'output_type')
    op.drop_column('tasks', 'goal_id')
    op.drop_column('tasks', 'agent_id')
    op.alter_column('task_suggestions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('task_suggestions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('task_history', 'to_status',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('waiting', 'ready', 'queued', 'in_progress', 'review', 'done', 'redesign', name='taskstatus'),
               existing_nullable=False)
    op.alter_column('task_history', 'from_status',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('waiting', 'ready', 'queued', 'in_progress', 'review', 'done', 'redesign', name='taskstatus'),
               existing_nullable=False)
    op.drop_column('projects', 'max_concurrent_tasks')
    op.drop_constraint(None, 'design_sessions', type_='foreignkey')
    op.drop_column('design_sessions', 'agent_id')
    op.drop_index('ix_cost_records_tenant', table_name='cost_records')
    op.drop_index('ix_cost_records_agent_month', table_name='cost_records')
    op.drop_index('ix_cost_records_agent', table_name='cost_records')
    op.drop_table('cost_records')
    op.drop_index('ix_goals_tenant', table_name='goals')
    op.drop_index('ix_goals_project', table_name='goals')
    op.drop_index('ix_goals_parent', table_name='goals')
    op.drop_table('goals')
    op.drop_index('ix_workers_tenant', table_name='workers')
    op.drop_index('ix_workers_status', table_name='workers')
    op.drop_table('workers')
    op.drop_index('ix_tenant_members_user', table_name='tenant_members')
    op.drop_index('ix_tenant_members_tenant_user', table_name='tenant_members')
    op.drop_table('tenant_members')
    op.drop_index('ix_agents_tenant_role', table_name='agents')
    op.drop_index('ix_agents_tenant', table_name='agents')
    op.drop_index('ix_agents_parent', table_name='agents')
    op.drop_table('agents')
    op.drop_table('tenants')
    # ### end Alembic commands ###
