"""add unique partial index for one default executor per tenant

Revision ID: 98d193d23a51
Revises: 2b216bbff5e3
Create Date: 2026-04-06 14:18:00.347514

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '98d193d23a51'
down_revision: Union[str, Sequence[str], None] = '2b216bbff5e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Fix existing data: keep only the most recently updated default per tenant
    op.execute("""
        UPDATE executor_configs SET is_default = false
        WHERE is_default = true
          AND id NOT IN (
            SELECT DISTINCT ON (tenant_id) id
            FROM executor_configs
            WHERE is_default = true
            ORDER BY tenant_id, updated_at DESC
          )
    """)
    op.create_index('uq_executor_configs_one_default_per_tenant', 'executor_configs', ['tenant_id'], unique=True, postgresql_where='is_default = true')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_executor_configs_one_default_per_tenant', table_name='executor_configs', postgresql_where='is_default = true')
    # ### end Alembic commands ###
