"""add workspace columns to projects

Revision ID: b06d1f663d08
Revises: 452b24310909
Create Date: 2026-04-06 15:21:30.778515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b06d1f663d08'
down_revision: Union[str, Sequence[str], None] = '452b24310909'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create the enum type first
    workspace_enum = sa.Enum('server_managed', 'local_import', 'github_connected', name='workspacetype')
    workspace_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('projects', sa.Column('workspace_type', workspace_enum, server_default='server_managed', nullable=False))
    op.add_column('projects', sa.Column('workspace_dir', sa.String(length=500), nullable=True))
    op.add_column('projects', sa.Column('github_repo_url', sa.String(length=500), nullable=True))
    op.add_column('projects', sa.Column('github_branch', sa.String(length=255), nullable=True))
    op.add_column('projects', sa.Column('github_token_encrypted', sa.Text(), nullable=True))

    # Migrate existing data: projects with repo_path → local_import, copy to workspace_dir
    op.execute("""
        UPDATE projects
        SET workspace_type = 'local_import', workspace_dir = repo_path
        WHERE repo_path IS NOT NULL AND repo_path != ''
    """)
    # Projects without repo_path → server_managed, auto-assign workspace_dir
    op.execute("""
        UPDATE projects
        SET workspace_dir = '/data/workspaces/' || id::text || '/'
        WHERE repo_path IS NULL OR repo_path = ''
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'github_token_encrypted')
    op.drop_column('projects', 'github_branch')
    op.drop_column('projects', 'github_repo_url')
    op.drop_column('projects', 'workspace_dir')
    op.drop_column('projects', 'workspace_type')
    # ### end Alembic commands ###
