"""add conversation_messages table

Revision ID: ec11c78b177c
Revises: f16bb0a5da85
Create Date: 2026-04-09 05:28:17.585927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'ec11c78b177c'
down_revision: Union[str, Sequence[str], None] = 'f16bb0a5da85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=True),
    sa.Column('agent_name', sa.String(length=255), nullable=True),
    sa.Column('actions', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('source', sa.String(length=20), server_default='web', nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('thread_ref', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conversation_messages_project_created', 'conversation_messages', ['project_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_conversation_messages_project_created', table_name='conversation_messages')
    op.drop_table('conversation_messages')
    # ### end Alembic commands ###
