"""add routing_keywords to agents

Revision ID: f16bb0a5da85
Revises: c9b64f368bc8
Create Date: 2026-04-08 14:08:14.490152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f16bb0a5da85'
down_revision: Union[str, Sequence[str], None] = 'c9b64f368bc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('routing_keywords', postgresql.JSON(astext_type=sa.Text()), server_default='[]', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'routing_keywords')
    # ### end Alembic commands ###
